### PR TITLE
chore(dependency): upgrade spring boot to latest version

### PR DESCRIPTION
**Pull request by yesid-bocanegra**
This will upgrade spring-core to 5.3.26

### CODE REVIEW

**Comment by yesid-bocanegra** [comment]
Tests have been run locally and no issues have risen. I have upgraded also the tests directory version

**Comment by yesid-bocanegra** [comment]
I don't feel confortabl upgrading the whole spring boot package, but at the same time it seems weird to just upgrade spring-core, please do let me know if this upgrade path is appropiate, otherwise I can only upgrade spring core.

**Comment by yesid-bocanegra** [comment]
Hi @dsyer have had a chance to take a llok at this PR?

**Comment by dsyer** [comment]
I just noticed it (github notifications are not very efficient). I guess it makes sense if the tests pass.

**Pull request merged**
